const Map<String, String> ar = {
  'sign up': 'تسجيل حساب',
  'about': 'حول التطبيق..',
  'Full Name': 'الاسم الكامل',
  'Password': 'كلمة السر',
  '3 years': '3 سنة',
  '4 years': '4 سنة',
  '5 years': '5 سنة',
  '6 years': '6 سنة',
  'submit': 'تسجيل',
  'Please complete your information': 'الرجاء إكمال إدخال معلوماتك',
  'Fail': 'فشل العملية',
  'Name & Password should more than 8 letters':
      'الاسم وكلمة السر يجب ان يكونو اكثر من 8 احرف',
  'Sign In': 'تسجيل الدخول',
  'Please enter your information': 'الرجاء إدخال معلوماتك',
  'Correct your information': 'صحح معلوماتك',
  '   What do you want to learn?': '    ماذا تريد أن تتعلم ؟؟  ',
  'Capital Chars': 'الانكليزية الكبيرة',
  'Small Chars': 'الانكليزية الصغيرة',
  'Numbers Chars': 'الأرقام',
  'Arabic Chars': 'الأحرف العربية',
  'Arabic Num': 'الأرقام العربية',
  'Account': 'الحساب',
  'rate': 'تقييم',
  'step': 'خطوة',
  'years': 'سنة ',
  'forParent': 'للآباء',
  'Settings': 'الاعدادات',
  'Change Color': 'تغيير الالوان',
  'LogOut': 'تسجيل الخروج',
  'Sound': 'الصوت',
  'Delete Account': 'حذف الحساب',
  'Learn': 'تعليم',
  'You must learn before': 'يجب عليك تعلمه قبلاً',
  'Train': 'تدريب',
  'Failed in train': 'فشل في التدريب',
  'You must train before': 'يجب عليك التدرب عليه قبلاً',
  'Test': 'فحص',
  'How many times do you want to learn?': 'كم مرة تريد أن تتدرب عليه؟',
  'Enter number from 1 to 5': 'أدخل رقم بين 1 و 5',
  'OK': 'تم',
  'You Failed': 'لقد رسبت',
  'You Finished': 'لقد انتهيت',
  'You must Train This letter very well': 'يجب عليك التدرب عليه جيداً',
  'Back to home': 'الرجوع الى الأحرف',
  'Try Test Again': 'اعادة الفحص',
  'You must Learn This letter very well': 'يجب عليك تعلمه جيداً',
  'Try Train Again': 'اعادة التدريب',
  'Change Lang': 'تغيير اللغة الى الانكليزية',
  'Progress in arabic chars..': 'التقدم في الأحرف العربية',
  'Progress in arabic num..': 'التقدم في الأرقام العربية',
  'Progress in capital chars..': 'التقدم في الأحرف الكبيرة',
  'Progress in small chars..': 'التقدم في الأحرف الصغيرة',
  'Progress in number chars..': 'التقدم في الأرقام الانكليزية',
  'show progress in Train or Test??': 'إظهار التقدم في التدريب أو الاختبار ؟',
  'Do it with right way': 'اكتب بشكل جيد',
  'Try again later': 'أعد المحاولة لاحقاً',
};
