const Map<String, String> en = {
  'sign up': 'Sign up',
  'about': 'About..',
  'Full Name': 'Full Name',
  'Password': 'Password',
  '3 years': '3 Years',
  '4 years': '4 Years',
  '5 years': '5 Years',
  '6 years': '6 Years',
  'submit': 'Submit',
  'Please complete your information': 'Please complete your information',
  'Fail': 'Fail',
  'Name & Password should more than 8 letters':
      'Name & Password should more than 8 letters',
  'Sign In': 'Sign In',
  'Please enter your information': 'Please enter your information',
  'Correct your information': 'Correct your information',
  '   What do you want to learn?': '   What do you want to learn?',
  'Capital Chars': 'Capital Chars',
  'Small Chars': 'Small Chars',
  'Numbers Chars': 'Numbers Chars',
  'Arabic Chars': 'Arabic Chars',
  'Arabic Num': 'Arabic Num',
  'Account': 'Account',
  'rate': 'Rate',
  'step': 'Step',
  'years': ' Years',
  'forParent': 'For Parent',
  'Settings': 'Settings',
  'Change Color': 'Change Color',
  'LogOut': 'LogOut',
  'Sound': 'Sound',
  'Delete Account': 'Delete Account',
  'Learn': 'Learn',
  'You must learn before': 'You must learn before',
  'Train': 'Train',
  'Failed in train': 'Failed in train',
  'You must train before': 'You must train before',
  'Test': 'Test',
  'How many times do you want to learn?':
      'How many times do you want to learn?',
  'Enter number from 1 to 5': 'Enter number from 1 to 5',
  'OK': 'OK',
  'You Failed': 'You Failed',
  'You Finished': 'You Finished',
  'You must Train This letter very well':
      'You must Train This letter very well',
  'Back to home page': 'Back to home page',
  'Try Test Again': 'Try Test Again',
  'You must Learn This letter very well':
      'You must Learn This letter very well',
  'Try Train Again': 'Try Train Again',
  'Change Lang': 'Change Lang To Arabic',
  'Progress in arabic chars..': 'Progress in arabic chars..',
  'Progress in arabic num..': 'Progress in arabic num..',
  'Progress in capital chars..': 'Progress in capital chars..',
  'Progress in small chars..': 'Progress in small chars..',
  'Progress in number chars..': 'Progress in number chars..',
  'show progress in Train or Test??': 'Show progress in Train or Test??',
  'Do it with right way': 'Do it with right way',
  'Try again later': 'Try again later',
};
